### ISSUE TITLE
Build problem on OSX 10.6.6, Node.js v0.4

### ISSUE THREAD

**Issue by pmcfadin** [node-pcap/node_pcap#19]
I'm doing a source build on Mac OSX 10.6.6 and the latest Node.js, v 0.4.0-pre. Also get this error when doing a npm install pcap. Here's the output:

pmcfadin$ node-waf configure build
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
Checking for library pcap                : yes 
'configure' finished successfully (0.857s)
Waf: Entering directory `/Volumes/Data/node_pcap/build'
[1/2] cxx: pcap_binding.cc -> build/default/pcap_binding_1.o
../pcap_binding.cc: In function ‘v8::Handle<v8::Value> Open(bool, const v8::Arguments&)’:
../pcap_binding.cc:141: error: ‘pcap_create’ was not declared in this scope
../pcap_binding.cc:147: error: ‘pcap_set_snaplen’ was not declared in this scope
../pcap_binding.cc:152: error: ‘pcap_set_promisc’ was not declared in this scope
../pcap_binding.cc:157: error: ‘pcap_set_buffer_size’ was not declared in this scope
../pcap_binding.cc:162: error: ‘pcap_set_timeout’ was not declared in this scope
../pcap_binding.cc:172: error: ‘pcap_activate’ was not declared in this scope
Waf: Leaving directory`/Volumes/Data/node_pcap/build'
Build failed:  -> task failed (err #1): 
    {task: cxx pcap_binding.cc -> pcap_binding_1.o}
